import { NewsItem, User, Comment } from "@/types";

// ─── SEED DATA ───────────────────────────────────────────────────────────────

export const USERS_DB: User[] = [
  {
    id: "admin-1",
    name: "علی رضایی",
    email: "admin@khabarlive.ir",
    role: "admin",
    avatar: "https://i.pravatar.cc/80?img=3",
    createdAt: "2024-01-01T00:00:00Z",
    newsCount: 142,
    isActive: true,
  },
  {
    id: "user-1",
    name: "سارا احمدی",
    email: "sara@example.com",
    role: "user",
    avatar: "https://i.pravatar.cc/80?img=5",
    createdAt: "2024-02-15T00:00:00Z",
    newsCount: 0,
    isActive: true,
  },
  {
    id: "user-2",
    name: "رضا ملکی",
    email: "reza@example.com",
    role: "user",
    avatar: "https://i.pravatar.cc/80?img=8",
    createdAt: "2024-03-10T00:00:00Z",
    newsCount: 0,
    isActive: true,
  },
];

// Hashed passwords map: email -> bcrypt hash of password
// admin: Admin@1234  |  users: Password@123
export const PASSWORDS_DB: Record<string, string> = {
  "admin@khabarlive.ir": "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lqpS", // Admin@1234
  "sara@example.com": "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",   // password
  "reza@example.com": "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",    // password
};

export const NEWS_DB: NewsItem[] = [
  {
    id: "news-1",
    title: "هوش مصنوعی AGI: دانشمندان اعلام کردند مرز بین هوش مصنوعی و هوش انسانی در حال محو شدن است",
    titleEn: "AGI: Scientists Say the Line Between AI and Human Intelligence Is Fading",
    titleAr: "الذكاء الاصطناعي العام: العلماء يعلنون تلاشي الحدود بين الذكاء الاصطناعي والبشري",
    excerpt: "گروهی از محققان دانشگاه MIT اعلام کردند که آخرین نسل مدل‌های هوش مصنوعی توانایی انجام بیش از ۹۵٪ وظایف شناختی انسانی را دارند.",
    excerptEn: "MIT researchers announced that the latest AI models can perform over 95% of human cognitive tasks.",
    excerptAr: "أعلن باحثو MIT أن أحدث نماذج الذكاء الاصطناعي قادرة على أداء أكثر من 95٪ من المهام المعرفية البشرية.",
    body: `<p>محققان دانشگاه MIT در پژوهشی که امروز در ژورنال Science منتشر شد، اعلام کردند که مرز بین هوش مصنوعی عمومی (AGI) و هوش انسانی به سرعت در حال محو شدن است.</p><h3>چه چیزی تغییر کرده؟</h3><p>آنچه این آزمایش را از تحقیقات قبلی متمایز می‌کند، توانایی مدل در استدلال خلاقانه و حل مسائل بدون سابقه است.</p><blockquote>«ما در آستانه یک تحول بنیادین در تاریخ بشریت قرار داریم.» — دکتر سارا چن، MIT</blockquote><h3>چالش‌های پیش رو</h3><p>با وجود این پیشرفت چشمگیر، کارشناسان نسبت به خطرات بالقوه این فناوری هشدار می‌دهند. مسائل اخلاقی مانند حریم خصوصی، اشتغال، و امنیت از مهم‌ترین چالش‌ها هستند.</p>`,
    bodyEn: `<p>MIT researchers published findings showing AI models now outperform average humans on over 95% of cognitive benchmarks.</p><h3>What Changed?</h3><p>Unlike previous systems that merely repeated learned patterns, these models can devise innovative solutions in entirely new situations.</p><blockquote>"We stand at the threshold of a fundamental transformation in human history." — Dr. Sarah Chen, MIT</blockquote>`,
    bodyAr: `<p>نشر باحثو MIT نتائج تُظهر أن نماذج الذكاء الاصطناعي تتفوق الآن على البشر في أكثر من 95٪ من المعايير المعرفية.</p><h3>ما الذي تغيّر؟</h3><p>على عكس الأنظمة السابقة، يمكن لهذه النماذج ابتكار حلول في مواقف جديدة تماماً.</p>`,
    category: "tech",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=900&q=80",
    author: "دکتر علی رضایی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=3",
    status: "published",
    views: 12400,
    createdAt: "2026-06-07T06:00:00Z",
    tags: ["هوش مصنوعی", "AGI", "MIT", "فناوری"],
    readingTime: "۵ دقیقه",
  },
  {
    id: "news-2",
    title: "بازار جهانی نفت با رکورد تاریخی جدید مواجه شد؛ قیمت هر بشکه از ۱۲۰ دلار گذشت",
    titleEn: "Global Oil Market Hits New Record: Barrel Price Exceeds $120",
    titleAr: "سوق النفط العالمي يواجه رقماً قياسياً جديداً: سعر البرميل يتجاوز 120 دولاراً",
    excerpt: "اوپک پلاس تصمیم گرفت تولید نفت را تا پایان سال محدود نگه دارد که این امر باعث جهش قیمت‌ها شد.",
    excerptEn: "OPEC+ decided to keep oil production limited until year-end, causing a price surge.",
    excerptAr: "قررت أوبك+ الإبقاء على إنتاج النفط محدوداً حتى نهاية العام، مما أدى إلى ارتفاع حاد في الأسعار.",
    body: `<p>بازار جهانی نفت دیروز با یک جهش تاریخی روبرو شد. قیمت هر بشکه نفت برنت برای اولین بار از سال ۲۰۲۲ از مرز ۱۲۰ دلار عبور کرد.</p><h3>دلایل افزایش قیمت</h3><p>تصمیم اوپک پلاس برای کاهش ۲ میلیون بشکه‌ای تولید روزانه، همراه با افزایش تقاضا از سوی اقتصادهای آسیایی، محرک اصلی این جهش قیمتی بود.</p>`,
    bodyEn: `<p>The global oil market experienced a historic surge yesterday. Brent crude crossed $120 per barrel for the first time since 2022.</p><h3>Reasons for the Price Increase</h3><p>OPEC+'s decision to cut daily production by 2 million barrels, combined with rising Asian demand, was the main driver.</p>`,
    bodyAr: `<p>شهد سوق النفط العالمي ارتفاعاً تاريخياً أمس، إذ تجاوز سعر خام برنت 120 دولاراً للبرميل للمرة الأولى منذ 2022.</p>`,
    category: "economy",
    image: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=900&q=80",
    author: "مهندس سارا احمدی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=5",
    status: "published",
    views: 8200,
    createdAt: "2026-06-07T05:15:00Z",
    tags: ["نفت", "اقتصاد", "اوپک"],
    readingTime: "۴ دقیقه",
  },
  {
    id: "news-3",
    title: "تیم ملی فوتبال ایران با پیروزی قاطع ۳ بر صفر راهی جام جهانی ۲۰۲۶ شد",
    titleEn: "Iran National Football Team Qualifies for 2026 World Cup with 3-0 Victory",
    titleAr: "المنتخب الإيراني يتأهل لكأس العالم 2026 بفوز حاسم 3-0",
    excerpt: "با این پیروزی در بازی پلی‌آف، ایران سهمیه حضور در جام جهانی آمریکا، کانادا و مکزیک را کسب کرد.",
    excerptEn: "With this playoff victory, Iran secured a spot in the USA/Canada/Mexico World Cup.",
    excerptAr: "بهذا الفوز في ملحق التصفيات، ضمن إيران مكاناً في كأس العالم المقام في أمريكا وكندا والمكسيك.",
    body: `<p>تیم ملی فوتبال ایران دیشب در یک بازی هیجان‌انگیز با نتیجه ۳ بر صفر حریف خود را شکست داد.</p><h3>گزارش بازی</h3><p>سردار آزمون در دقیقه ۲۳ اولین گل را به ثمر رساند. محرمی در نیمه دوم با دو گل فوق‌العاده بازی را به نتیجه تاریخی تبدیل کرد.</p><blockquote>«این پیروزی به تمام ملت ایران تعلق دارد.»</blockquote>`,
    bodyEn: `<p>Iran's national football team defeated their opponents 3-0 in a thrilling playoff match.</p><h3>Match Report</h3><p>Sardar Azmoun scored the opener in the 23rd minute, while Mohammadi added two more in the second half.</p>`,
    bodyAr: `<p>هزم المنتخب الإيراني منافسه بنتيجة 3-0 في مباراة مثيرة.</p>`,
    category: "sport",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=900&q=80",
    author: "رضا ملکی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=8",
    status: "published",
    views: 45100,
    createdAt: "2026-06-07T04:00:00Z",
    tags: ["فوتبال", "تیم ملی", "جام جهانی"],
    readingTime: "۳ دقیقه",
  },
  {
    id: "news-4",
    title: "سازمان ملل: بحران آب در خاورمیانه به نقطه بحرانی رسیده و نیاز به اقدام فوری دارد",
    titleEn: "UN: Middle East Water Crisis Reaches Critical Point, Urgent Action Needed",
    titleAr: "الأمم المتحدة: أزمة المياه في الشرق الأوسط وصلت لنقطة حرجة",
    excerpt: "گزارش سازمان ملل هشدار می‌دهد که تا سال ۲۰۳۵، بیش از ۲۰۰ میلیون نفر با کمبود شدید آب مواجه خواهند شد.",
    excerptEn: "UN report warns that by 2035, over 200 million people will face severe water shortages.",
    excerptAr: "يحذر تقرير الأمم المتحدة من أنه بحلول 2035 سيواجه أكثر من 200 مليون شخص شحاً حاداً في المياه.",
    body: `<p>سازمان ملل متحد در گزارشی هشداردهنده اعلام کرد که بحران آب در منطقه خاورمیانه به نقطه‌ای غیرقابل بازگشت نزدیک می‌شود.</p><h3>ابعاد بحران</h3><p>پیش‌بینی‌ها نشان می‌دهد که تا سال ۲۰۳۵، بیش از ۲۰۰ میلیون نفر در معرض کمبود شدید آب قرار خواهند گرفت.</p>`,
    bodyEn: `<p>The UN warned that the Middle East water crisis is approaching a point of no return.</p>`,
    bodyAr: `<p>حذّرت الأمم المتحدة من أن أزمة المياه في الشرق الأوسط تقترب من نقطة اللاعودة.</p>`,
    category: "world",
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=900&q=80",
    author: "لیلا کریمی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=10",
    status: "published",
    views: 6700,
    createdAt: "2026-06-07T03:00:00Z",
    tags: ["آب", "خاورمیانه", "سازمان ملل"],
    readingTime: "۶ دقیقه",
  },
  {
    id: "news-5",
    title: "اپل از iPhone 18 رونمایی کرد: صفحه‌نمایش هولوگرافیک و باتری ۵ روزه",
    titleEn: "Apple Unveils iPhone 18: Holographic Display and 5-Day Battery",
    titleAr: "آبل تكشف عن iPhone 18: شاشة هولوغرافية وبطارية لـ 5 أيام",
    excerpt: "اپل در رویداد سالانه خود، مدل جدید آیفون را با فناوری‌های انقلابی معرفی کرد.",
    excerptEn: "Apple introduced the new iPhone model with revolutionary technologies at its annual event.",
    excerptAr: "قدّمت آبل نموذج iPhone الجديد بتقنيات ثورية في حدثها السنوي.",
    body: `<p>اپل دیروز در رویداد سالانه‌اش از iPhone 18 رونمایی کرد. این دستگاه اولین گوشی هوشمند تجاری دارای صفحه‌نمایش هولوگرافیک در بازار است.</p><h3>ویژگی‌های انقلابی</h3><p>باتری جدید این دستگاه با فناوری گرافن، می‌تواند تا ۵ روز کامل با یک شارژ دوام بیاورد.</p>`,
    bodyEn: `<p>Apple unveiled the iPhone 18 yesterday, the world's first commercial smartphone with a holographic display.</p><h3>Revolutionary Features</h3><p>The new graphene battery lasts up to 5 full days on a single charge.</p>`,
    bodyAr: `<p>كشفت آبل عن iPhone 18 أمس، أول هاتف ذكي تجاري يحمل شاشة هولوغرافية.</p>`,
    category: "tech",
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=900&q=80",
    author: "آرش محمودی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=15",
    status: "published",
    views: 28900,
    createdAt: "2026-06-06T22:00:00Z",
    tags: ["اپل", "آیفون", "موبایل"],
    readingTime: "۴ دقیقه",
  },
  {
    id: "news-6",
    title: "نشست بریکس: ۲۴ کشور جدید درخواست عضویت دادند",
    titleEn: "BRICS Summit: 24 New Countries Apply for Membership",
    titleAr: "قمة بريكس: 24 دولة جديدة تتقدم بطلبات العضوية",
    excerpt: "در اجلاس این هفته بریکس، درخواست عضویت ۲۴ کشور به صورت رسمی به دبیرخانه ارسال شد.",
    excerptEn: "At this week's BRICS summit, 24 countries formally submitted membership applications.",
    excerptAr: "في قمة بريكس هذا الأسبوع، قدّمت 24 دولة طلبات عضوية رسمية.",
    body: `<p>اجلاس بریکس این هفته با یک خبر مهم همراه بود: ۲۴ کشور جدید درخواست رسمی عضویت را ارسال کردند.</p><h3>تحول در نظم اقتصاد جهانی</h3><p>این رویداد نشان‌دهنده تمایل فزاینده کشورها برای یافتن جایگزین‌هایی در برابر سیستم مالی غرب‌محور است.</p>`,
    bodyEn: `<p>This week's BRICS summit was accompanied by a major announcement: 24 new countries submitted formal membership applications.</p>`,
    bodyAr: `<p>رافقت قمة بريكس هذا الأسبوع إعلانات مهمة بتقدم 24 دولة جديدة بطلبات عضوية رسمية.</p>`,
    category: "politics",
    image: "https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8?w=900&q=80",
    author: "فرزانه کاظمی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=20",
    status: "published",
    views: 4100,
    createdAt: "2026-06-06T18:00:00Z",
    tags: ["بریکس", "سیاست بین‌الملل"],
    readingTime: "۵ دقیقه",
  },
  {
    id: "news-7",
    title: "جشنواره فیلم کن: فیلم ایرانی «سایه‌های دور» جایزه طلایی نخل را از آن خود کرد",
    titleEn: "Cannes Film Festival: Iranian Film 'Distant Shadows' Wins Palme d'Or",
    titleAr: "مهرجان كان: الفيلم الإيراني 'ظلال بعيدة' يفوز بالسعفة الذهبية",
    excerpt: "کارگردان جوان ایرانی با اثری درباره زندگی مهاجران، بزرگترین جایزه سینمای جهان را برد.",
    excerptEn: "A young Iranian director won cinema's greatest prize with a film about migrant life.",
    excerptAr: "مخرج إيراني شاب يفوز بأكبر جوائز السينما العالمية بفيلم عن حياة المهاجرين.",
    body: `<p>در هفتادوهشتمین دوره جشنواره فیلم کن، کارگردان جوان ایرانی موفق شد جایزه نخل طلایی را کسب کند.</p><h3>درباره فیلم</h3><p>«سایه‌های دور» روایتی تکان‌دهنده از زندگی یک خانواده مهاجر ایرانی در اروپاست.</p>`,
    bodyEn: `<p>At the 78th Cannes Film Festival, a young Iranian director won the Palme d'Or.</p><h3>About the Film</h3><p>'Distant Shadows' is a moving portrayal of an Iranian immigrant family in Europe.</p>`,
    bodyAr: `<p>في الدورة الثامنة والسبعين لمهرجان كان، فاز مخرج إيراني شاب بالسعفة الذهبية.</p>`,
    category: "culture",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=900&q=80",
    author: "نیلوفر رحیمی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=25",
    status: "published",
    views: 18300,
    createdAt: "2026-06-06T14:00:00Z",
    tags: ["سینما", "جشنواره کن", "فرهنگ"],
    readingTime: "۳ دقیقه",
  },
  {
    id: "news-8",
    title: "بورس تهران ۳.۸ درصد رشد کرد؛ صنعت خودرو و پتروشیمی پیشتاز بودند",
    titleEn: "Tehran Stock Exchange Grows 3.8%: Auto and Petrochemical Sectors Lead",
    titleAr: "بورصة طهران ترتفع 3.8٪: قطاعا السيارات والبتروكيماويات في الصدارة",
    excerpt: "شاخص کل بورس تهران با رشد چشمگیر ۳.۸ درصدی روز خوبی را پشت سر گذاشت.",
    excerptEn: "Tehran's main stock index grew by a remarkable 3.8% yesterday.",
    excerptAr: "ارتفع المؤشر الرئيسي لبورصة طهران بنسبة ملحوظة بلغت 3.8٪ أمس.",
    body: `<p>بورس اوراق بهادار تهران روز گذشته یکی از بهترین روزهای خود در سال جاری را تجربه کرد.</p><h3>پیشتازان بازار</h3><p>سهام شرکت‌های پتروشیمی و خودروسازی بیشترین رشد را داشتند.</p>`,
    bodyEn: `<p>The Tehran Stock Exchange had one of its best days of the year yesterday.</p>`,
    bodyAr: `<p>شهدت بورصة طهران أمس أحد أفضل أيامها في العام الحالي.</p>`,
    category: "economy",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=900&q=80",
    author: "علیرضا تهرانی",
    authorId: "admin-1",
    authorAvatar: "https://i.pravatar.cc/80?img=30",
    status: "published",
    views: 9800,
    createdAt: "2026-06-06T10:00:00Z",
    tags: ["بورس", "اقتصاد", "سرمایه‌گذاری"],
    readingTime: "۳ دقیقه",
  },
];

export const COMMENTS_DB: Comment[] = [
  { id: "c-1", newsId: "news-1", newsTitle: "هوش مصنوعی AGI", userId: "user-1", userName: "سارا احمدی", userAvatar: "https://i.pravatar.cc/40?img=5", text: "مقاله بسیار جالبی بود، ممنون از تیم خبری!", status: "approved", createdAt: "2026-06-07T07:00:00Z" },
  { id: "c-2", newsId: "news-2", newsTitle: "بازار نفت", userId: "user-2", userName: "رضا ملکی", userAvatar: "https://i.pravatar.cc/40?img=8", text: "چرا قیمت نفت اینقدر سریع بالا رفته؟", status: "pending", createdAt: "2026-06-07T06:30:00Z" },
  { id: "c-3", newsId: "news-3", newsTitle: "تیم ملی فوتبال", userId: "user-1", userName: "سارا احمدی", userAvatar: "https://i.pravatar.cc/40?img=5", text: "واقعاً افتخار کردم بهشون!", status: "approved", createdAt: "2026-06-07T05:00:00Z" },
  { id: "c-4", newsId: "news-7", newsTitle: "جشنواره کن", userId: "user-2", userName: "رضا ملکی", userAvatar: "https://i.pravatar.cc/40?img=8", text: "آیا این فیلم به زودی در ایران اکران می‌شود؟", status: "pending", createdAt: "2026-06-06T20:00:00Z" },
  { id: "c-5", newsId: "news-8", newsTitle: "بورس تهران", userId: "user-1", userName: "سارا احمدی", userAvatar: "https://i.pravatar.cc/40?img=5", text: "اطلاعات دقیق و به موقع. ممنون.", status: "pending", createdAt: "2026-06-06T15:00:00Z" },
];
